include:
  - deploy/compose.yml

services:
  gui:
    build:
      context: .
      dockerfile: deploy/gui/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://orion.harville.dev/api}
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-https://orion.harville.dev/api}  # if not set, use production API url
    profiles:
      - gui
