
services:
  gui:
    build:
      context: .
      dockerfile: deploy/gui/Dockerfile
      args:
         VITE_API_URL: ${VITE_API_URL:-https://orion.harville.dev/api}
    image: "ghcr.io/isaiah-harville/orion/orion-gui:latest"
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://orion.harville.dev/api}
    ports:
      - "5173:5173"
    profiles:
      - gui

  api:
    build:
      context: .
      dockerfile: deploy/api/Dockerfile
      args:
         VITE_API_URL: ${VITE_API_URL:-https://orion.harville.dev/api}
    image: "ghcr.io/isaiah-harville/orion/orion-api:latest"
    environment:
      SERVICE: api
      SCAN_DIR: /app/scans
      KERAS_BACKEND: torch
      TORNET_ROOT: data/TorNet
      VITE_API_URL: ${VITE_API_URL:-production}
    ports:
      - "5171:5171"

networks:
  default:
    name: orion
