---
apiVersion: v1
kind: Service
metadata:
  name: orion
  labels:
    app: orion
spec:
  selector:
    app: orion
  ports:
    - name: gui
      port: 80
      targetPort: gui
    - name: api
      port: 5171
      targetPort: api
