services:
  api:
    build:
      context: ../../
      dockerfile: deploy/api/Dockerfile
    ports:
      - "8000:8000"
    container_name: orion-api
    environment:
      - SCAN_DIR=/app/scans
      - KERAS_BACKEND=torch
      - TORNET_ROOT=data/TorNet
      - VITE_API_URL=${VITE_API_URL:-production}  # if not set, defaults to production

    # volumes:
      # - ../../data/TorNet:/app/data/TorNet
