apiVersion: v1
kind: Service
metadata:
  name: {{ include "orion.fullname" . }}-api
  labels:
    {{- include "orion.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "orion.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orion.fullname" . }}-gui
  labels:
    {{- include "orion.labels" . | nindent 4 }}
    app.kubernetes.io/component: gui
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "orion.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gui
  ports:
    - name: gui
      port: {{ .Values.service.guiPort }}
      targetPort: gui
