services:
  fast:
    build:
      context: ../../
      dockerfile: deploy/fast/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SCAN_DIR=/app/scans
      - KERAS_BACKEND=torch
      - TORNET_ROOT=data/TorNet
    volumes:
      - ./scans:/app/scans
      - ../../data/TorNet:/app/data/TorNet
